# Generated by Django 6.0.5 on 2026-05-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='opening_balance',
        ),
    ]
