# Generated by Django 6.0.5 on 2026-05-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_account_name_wallet_account_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransfer',
            options={'ordering': ['-transfer_date', '-id']},
        ),
        migrations.RenameField(
            model_name='wallettransfer',
            old_name='from_wallet',
            new_name='send_from',
        ),
        migrations.RenameField(
            model_name='wallettransfer',
            old_name='to_wallet',
            new_name='send_to',
        ),
    ]
