# Generated by Django 6.0.5 on 2026-05-29 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_wallettransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransfer',
            options={},
        ),
        migrations.RenameField(
            model_name='wallettransfer',
            old_name='send_from',
            new_name='from_wallet',
        ),
        migrations.RenameField(
            model_name='wallettransfer',
            old_name='send_to',
            new_name='to_wallet',
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='transfer_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
