# Generated by Django 6.0.5 on 2026-05-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_alter_wallettransfer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransfer',
            options={'ordering': ['-transfer_date', '-id']},
        ),
    ]
