# Generated by Django 6.0.5 on 2026-05-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_wallettransfer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_group',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
    ]
