# Generated by Django 6.0.5 on 2026-05-30 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_wallet_wallet_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['name'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AlterModelOptions(
            name='wallettransfer',
            options={'ordering': ['-transfer_date', '-id'], 'verbose_name': 'Wallet Transfer', 'verbose_name_plural': 'Wallet Transfers'},
        ),
        migrations.AlterField(
            model_name='wallet',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='wallettransfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transfers', to=settings.AUTH_USER_MODEL),
        ),
    ]
